language: java

script: ./gradlew clean build jacocoTestReport

before_install:
  - "export DISPLAY=:99.0"
services:
  - xvfb
jdk:
  - openjdk8

after_success:
  - ./gradlew jacocoTestReport coveralls